version: '3.8'
services:
  react-app:
    build: .
    container_name: react-app-dev
    image: react-app-dev:latest
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      NODE_ENV: development
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

networks:
  app-network:
    driver: bridge
