services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    image: ${DOCKER_USERNAME}/react-app:latest  
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
