version: '3.8'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-app-prod
    image: ${DOCKER_USERNAME}/react-app:latest  # Thay thế DOCKER_USERNAME bằng username Docker Hub của bạn
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
