services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    image: tranvanhung26092002/react-app:latest  # Thay thế DOCKER_USERNAME bằng username Docker Hub của bạn
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
