version: '3.8'
services:
  react-app:
    build: .
    container_name: react-app-dev
    image: react-app-dev:latest  # Đặt tên image duy nhất
    ports:
      - "5173:5173"  # Ánh xạ cổng 5173
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
